# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a85a474ab2e5406bfff6b5ca0b6d932a42cd954f8339e25ad5c7b44740b3d6d3084b642256f4ff93aa00bbcf8c28a70531e79c08dc412b9858bdb1059cf34b93

test:
  secret_key_base: e7b597d0ba75061dbddfc0348ac8b01ce4ace837ceb1bdd26d25e6fe32c5246e3c6ef42fd4d06c16205ee25ab43d8717738de99da2966b88219a77eecad23362

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
